### PR TITLE
Remove Python 3.2 travis build

### PR DESCRIPTION
**Pull request by jayvdb**
pip and others have de-supported Python 3.2,
and the build script currently fails while
tox is setting up the environment.

### CODE REVIEW

**Comment by brechtm** [comment]
I wouldn't drop 3.2 support unless there's something we really need that's not supported by it.

Why is tox failing? Because pip doesn't support Python 3.2? Can you link to a build log?

**Comment by jayvdb** [comment]
https://travis-ci.org/jayvdb/citeproc-py/jobs/109133059

```
$ tox

GLOB sdist-make: /home/travis/build/jayvdb/citeproc-py/setup.py

py32 create: /home/travis/build/jayvdb/citeproc-py/.tox/py32

ERROR: invocation failed (exit code 1), logfile: /home/travis/build/jayvdb/citeproc-py/.tox/py32/log/py32-0.log

ERROR: actionid: py32

msg: getenv

cmdargs: ['/home/travis/virtualenv/python3.2.5/bin/python', '-m', 'virtualenv', '--python', '/home/travis/virtualenv/python3.2.5/bin/python3.2', 'py32']

env: {'PYTHON_CFLAGS': '-g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security', 'COMPOSER_NO_INTERACTION': '1', 'rvm_stored_umask': '0002', 'CONTINUOUS_INTEGRATION': 'true', 'rvm_version': '1.26.8 (1.26.8)', 'GOROOT': '/home/travis/.gimme/versions/go1.4.1.linux.amd64', 'NVM_IOJS_ORG_VERSION_LISTING': 'https://iojs.org/dist/index.tab', 'rvm_without_gems': 'rubygems-bundler', 'rvm_path': '/home/travis/.rvm', 'RACK_ENV': 'test', 'SSH_CLIENT': '172.17.42.1 56431 22', 'rvm_project_rvmrc': '0', 'LOGNAME': 'travis', 'USER': 'travis', 'NVM_DIR': '/home/travis/.nvm', 'HOME': '/home/travis', 'TRAVIS_REPO_SLUG': 'jayvdb/citeproc-py', 'PATH': '/home/travis/build/jayvdb/citeproc-py/.tox/py32/bin:/home/travis/virtualenv/python3.2.5/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.5.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.5.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.5.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin', 'TRAVIS_PULL_REQUEST': 'false', 'NVM_IOJS_ORG_MIRROR': 'https://iojs.org/dist', 'rvm_autoupdate_flag': '0', 'rvm_silence_path_mismatch_check_flag': '1', 'PS4': '+', 'LANG': 'en_US.UTF-8', 'JRUBY_OPTS': '--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xcext.enabled=false -J-Xss2m -Xcompile.invokedynamic=false', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'TRAVIS_COMMIT': '6730cb3cb7a7893ec618dbb1430cc4181dac38f0', 'rvm_prefix': '/home/travis', 'TRAVIS_BRANCH': 'page-number-parsing', 'SHLVL': '3', 'rvm_with_default_gems': 'rake=~>10.2.2 bundler=~>1.6.0', 'PWD': '/home/travis/build/jayvdb/citeproc-py', 'MERB_ENV': 'test', 'VIRTUAL_ENV': '/home/travis/build/jayvdb/citeproc-py/.tox/py32', 'NVM_BIN': '/home/travis/.nvm/v0.10.36/bin', 'NVM_PATH': '/home/travis/.nvm/v0.10.36/lib/node', 'GIT_ASKPASS': 'echo', 'VIRTUAL_ENV_DISABLE_PROMPT': 'true', 'MANPATH': '/home/travis/.nvm/v0.10.36/share/man:/usr/local/clang-3.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man', 'PYTHONHASHSEED': '3035213736', '_system_arch': 'x86_64', 'HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE': 'true', 'GEM_PATH': '/home/travis/.rvm/gems/ruby-1.9.3-p551:/home/travis/.rvm/gems/ruby-1.9.3-p551@global', 'rvm_bin_path': '/home/travis/.rvm/bin', 'LC_CTYPE': 'en_US.UTF-8', 'CI': 'true', 'TOXENV': 'py32', 'rvm_loaded_flag': '1', 'RAILS_ENV': 'test', 'DEBIAN_FRONTEND': 'noninteractive', 'rvm_user_install_flag': '1', 'TRAVIS_JOB_NUMBER': '80.2', 'IRBRC': '/home/travis/.rvm/rubies/ruby-1.9.3-p551/.irbrc', 'TRAVIS_BUILD_ID': '109133057', 'TRAVIS_SECURE_ENV_VARS': 'false', 'MY_RUBY_HOME': '/home/travis/.rvm/rubies/ruby-1.9.3-p551', 'rvm_max_time_flag': '5', 'RUBY_VERSION': 'ruby-1.9.3-p551', 'LC_ALL': 'en_US.UTF-8', '_system_type': 'Linux', '_': '/home/travis/virtualenv/python3.2.5/bin/tox', 'TRAVIS_TAG': '', 'TRAVIS_JOB_ID': '109133059', 'JAVA_HOME': '/usr/lib/jvm/java-7-oracle', 'TRAVIS': 'true', 'PYTHON_CONFIGURE_OPTS': '--enable-unicode=ucs4 --with-wide-unicode --enable-shared --enable-ipv6 --enable-loadable-sqlite-extensions --with-computed-gotos', 'SSH_TTY': '/dev/pts/1', 'OLDPWD': '/home/travis/build', 'TRAVIS_LANGUAGE': 'python', 'TRAVIS_BUILD_NUMBER': '80', 'TRAVIS_BUILD_DIR': '/home/travis/build/jayvdb/citeproc-py', 'TRAVIS_PYTHON_VERSION': '3.2', '_system_name': 'Ubuntu', 'TRAVIS_OS_NAME': 'linux', '_system_version': '12.04', 'PIP_DISABLE_PIP_VERSION_CHECK': '1', 'TRAVIS_COMMIT_RANGE': '4c6a2a7751fe...6730cb3cb7a7', 'MAIL': '/var/mail/travis', 'SSH_CONNECTION': '172.17.42.1 56431 172.17.2.27 22', 'GEM_HOME': '/home/travis/.rvm/gems/ruby-1.9.3-p551', 'HAS_JOSH_K_SEAL_OF_APPROVAL': 'true', 'NVM_NODEJS_ORG_MIRROR': 'https://nodejs.org/dist'}

/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

Using real prefix '/opt/python/3.2.5'

New python executable in /home/travis/build/jayvdb/citeproc-py/.tox/py32/bin/python3.2

Also creating executable in /home/travis/build/jayvdb/citeproc-py/.tox/py32/bin/python

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv.py", line 2304, in <module>

    main()

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv.py", line 705, in main

    symlink=options.symlink)

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv.py", line 924, in create_environment

    download=download,

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv.py", line 843, in install_wheel

    cert_data = pkgutil.get_data("pip._vendor.requests", "cacert.pem")

  File "/opt/python/3.2.5/lib/python3.2/pkgutil.py", line 573, in get_data

    loader = get_loader(package)

  File "/opt/python/3.2.5/lib/python3.2/pkgutil.py", line 461, in get_loader

    return find_loader(fullname)

  File "/opt/python/3.2.5/lib/python3.2/pkgutil.py", line 471, in find_loader

    for importer in iter_importers(fullname):

  File "/opt/python/3.2.5/lib/python3.2/pkgutil.py", line 427, in iter_importers

    __import__(pkg)

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/download.py", line 35, in <module>

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/utils/ui.py", line 15, in <module>

  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/_vendor/progress/bar.py", line 48

    empty_fill = u'∙'

                      ^

SyntaxError: invalid syntax

Running virtualenv with interpreter /home/travis/virtualenv/python3.2.5/bin/python3.2
```

**Comment by jayvdb** [comment]
virtualenv 14 dropped support for Python 3.2  https://virtualenv.pypa.io/en/latest/changes.html
pip 8 dropped support for Python 3.2 https://pip.pypa.io/en/stable/news/
coveragepy also dropped support for Python 3.2 https://coverage.readthedocs.org/en/coverage-4.0.3/

If you're keen to keep Python 3.2 support, it looks like the workaround would be to install&pin an old version of virtualenv and coveragepy to versions that did support Python 3.2.
https://github.com/travis-ci/travis-ci/issues/5517
https://github.com/travis-ci/travis-ci/issues/5485#issuecomment-173837358

That should buy our Python 3.2 support some time, until the old version of virtualenv and coveragepy becomes incompatible with other software.

**Comment by jayvdb** [comment]
Python 3.2 build fixed with #60 .

**Pull request closed without merging**
