### PR TITLE
Read locales.json as utf-8 to fix windows read error

### LINKED ISSUE #106: UnicodeDecodeError when importing citeproc on Windows 10
Using version 0.5.1. When I open a Python 3.8 terminal and call `import citeproc` on Windows, I get:
```
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import citeproc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\site-packages\citeproc\__init__.py", line 43, in <module>
    locales_json = json.load(file)
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Ryan\miniconda3\envs\test_due\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1266: character maps to <undefined>
```

This seems to be fixed by changing 
https://github.com/brechtm/citeproc-py/blob/7ebd0d6ab983d2632acc34916c25587c20e056f4/citeproc/__init__.py#L42
to 
`with open(os.path.join(LOCALES_PATH, 'locales.json'), encoding='utf-8') as file:`

### PR DESCRIPTION
**Pull request by rly**
Fix #106

This works locally on my Windows 10 machine. Please let me know if I should add anything else.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thank you @rly!  I will give it a try later on while also trying to figure out WTF is so special about installing on windows which ruins installation in just introduced github actions: https://github.com/brechtm/citeproc-py/runs/1494655431?check_suite_focus=true

**Comment by rly** [comment]
re: installing on Windows, I filed an issue ticket about that here: https://github.com/djc/rnc2rng/issues/31

**Comment by rly** [comment]
A workaround in citeproc-py may be, within setup.py, to change working directory to citeproc/data/schema and then call `rnc2rng.load`

**Comment by yarikoptic** [comment]
> A workaround in citeproc-py may be, within `setup.py`, to change working directory to "citeproc/data/schema" and then call `rnc2rng.load`

implemented just that in #110 , I will now add your fix as part of that PR since that is what it is tripping on now

**Comment by yarikoptic** [comment]
https://github.com/brechtm/citeproc-py/pull/110 showed that this fix works, subsequent failures from additional testing (on windows and mac 3.5) are AFAIK unrelated.  Thus merging this PR

**Comment by rly** [comment]
Would it be possible to make a release of citeproc with this bugfix so that it can run on Windows?

**Pull request merged**
