### PR TITLE
Replace trang with Python package rnc2rng

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
I would have liked to amend my patch so it could be merged :/

**Comment by brechtm** [comment]
I'm sorry John. I'm not sure I understand the implications of this. Does this complicate things for you when working on your fork?

I really appreciate your contributions, even though I have little time to incorporate them*. Let me know what I can do in the future to make things easier for you.

* I'll try to process all the current open pull requests ASAP. Perhaps I should reserve some time each month to process contributions, as this would be more motivating...

**Comment by jayvdb** [comment]
In this case it was more that I put a lot of effort into getting `rnc2rng` to a point that it was able to be used, and would have liked my commit to have been integrated to show my boss for the time spent on it.

**Comment by brechtm** [comment]
Ah, I understand. In the future, I'll merge in pull requests and amend them or create additional commits if necessary.

**Comment by jayvdb** [comment]
I am more than happy to amend patches during the pull request process before they are merged. (I wish it was called code review instead of pull request)

**Pull request closed without merging**
