### PR TITLE
Progress test-suite, remove no longer failing tests, add new ones

### PR DESCRIPTION
**Pull request by yarikoptic**
Sits on top of #115 so we could get a clean test run on CI.  Only two commits relevant:
- progress test-suite to current master (from Dec 2020) from originally used from 2017 IIRC, and remove no longer failing lists
- list newly failing tests (so not really a fix but at least we would make CI green again ;-))

FTR here is the command (also in commit msg) I used to remove no longer failing ones:

    xsel -o | while read t; do sed -n -e "/$t/d" tests/failing_tests.txt ; done

### CODE REVIEW

**Comment by brechtm** [comment]
To avoid regressions, you should add only those tests to the ignored list that have been added to the test suite.

**Comment by yarikoptic** [comment]
> To avoid regressions, you should add only those tests to the ignored list that have been added to the test suite.

rright... would anyone have time to address regressions ATM though?

It seems that the "stable grounds" were lost somehow (CI fails on master) and should be regained first.

FTR -- osx 3.6 fail 
<details>
<summary>seems due to inability to submit to codecov... IMHO should not fail the test itself!</summary> 

```shell
 py36 run-test: commands[2] | python /Users/runner/work/citeproc-py/citeproc-py/coveralls.py
  Submitting coverage to coveralls.io...
  Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
  Traceback (most recent call last):
    File "/Users/runner/work/citeproc-py/citeproc-py/.tox/py36/lib/python3.6/site-packages/coveralls/api.py", line 257, in wear
      response.raise_for_status()
    File "/Users/runner/work/citeproc-py/citeproc-py/.tox/py36/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/Users/runner/work/citeproc-py/citeproc-py/.tox/py36/lib/python3.6/site-packages/coveralls/cli.py", line 85, in main
      result = coverallz.wear()
    File "/Users/runner/work/citeproc-py/citeproc-py/.tox/py36/lib/python3.6/site-packages/coveralls/api.py", line 261, in wear
      'Could not submit coverage: {}'.format(e)) from e
  coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
  resubmitting with id None
  ERROR: InvocationError for command /Users/runner/work/citeproc-py/citeproc-py/.tox/py36/bin/python /Users/runner/work/citeproc-py/citeproc-py/coveralls.py (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36: commands failed
Error: Process completed with exit code 1.
```
</details>

Windows -- seems to just have some extra issue (attn @rly) which fails some tests then from the suite :-/ eg

```
  Checking out the specified commit...
  New failing tests:
   bugreports_ContextualPluralWithMainItemFields
   bugreports_MissingItemInJoin
   bugreports_NumberInMacroWithVerticalAlign
   bugreports_SelfLink
   bugreports_SingleQuoteXml
...
```

**Comment by brechtm** [comment]
PS. Python 3.5 support can de dropped, as it is no longer supported itself.

**Comment by yarikoptic** [comment]
yeah, let's close this for now

**Pull request closed without merging**
