### PR TITLE
Move setup_requires into pyproject.toml

### PR DESCRIPTION
**Pull request by yarikoptic**
Hopefully this helps to resolve gotcha with python 3.5, but also it is
the way forward in long(er) term since setup_requires is deprecated etc

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo -- works now!  Those failing are seems to be failing for 
```
  git clone https://github.com/citation-style-language/test-suite.git D:\a\citeproc-py\citeproc-py\tests\test-suite
  Checking out the specified commit...
  New failing tests:
   bugreports_ContextualPluralWithMainItemFields
   bugreports_SelfLink
   bugreports_SingleQuoteXml
   condition_SingletonIfMatchNone
...
```
as in #114 now, and which is a separate issue.  If @brechtm wouldn't object -- I would merge this one.

**Comment by brechtm** [comment]
Sorry to be a PITA, but we should really avoid regressions, i.e. no changes should cause tests to fail that didn't fail before. That is the whole point of tracking the failing tests 😄

**Comment by yarikoptic** [comment]
Regression failures already sneaked in, but came unnoticed since there is no CRON CI run AFAIK.
This PR nohow effects the tests themselves - it only addresses the ability to install and to run the tests, so IMHO could and should be merged.

**Comment by yarikoptic** [comment]
**but** may be it is new versions of rnc2rng to blame?  let me look into which one was last successfully run with...

**Comment by brechtm** [comment]
> Regression failures already sneaked in, but came unnoticed since there is no CRON CI run AFAIK.

CI jobs run for each commit on master and PR, no? In any case, we should first fix failing tests before merging in new changes.

The l[ast commits on master](https://github.com/brechtm/citeproc-py/actions/workflows/test.yml?query=branch%3Amaster) seem to be free from failing tests though (but there were other issues with CI).

> This PR nohow effects the tests themselves - it only addresses the ability to install and to run the tests, so IMHO could and should be merged.

👍

**Comment by yarikoptic** [comment]
last commit on master 4 months ago.  Since then rnc2rng etc got newer releases, no tests for citeproc were ran, so we don't know what new broke it.

**Comment by brechtm** [comment]
> last commit on master 4 months ago. Since then rnc2rng etc got newer releases, no tests for citeproc were ran, so we don't know what new broke it.

Moving to Poetry for dependency management would prevent these issues as it locks dependencies at specific versions. Of course, that will require more work...

**Comment by yarikoptic** [comment]
FTR: windows tests (and mac 3.6) were failing on github actions 4 months ago as well upon PR #109 merge. PR itself was green since for it there were no yet windows CI runs.  Needed fixes on rnc2rng side were supposed to release in 2.6.3

**Comment by yarikoptic** [comment]
uff... I am out of ideas on how we can manage to please older (but 3.6 is still supported) versions of python. 
Given that https://github.com/brechtm/citeproc-py/pull/114 is all green on travis even with 3.9 added, suggests that moving to pyproject.toml relates to indigestions, and it is not per se about version of `rnc2rng`.  My last attempt will be to bring back original rnc2rng specs and specify in both `pyproject.toml` and `setup_requires`.

**Comment by yarikoptic** [comment]
> Moving to Poetry for dependency management would prevent these issues as it locks dependencies at specific versions. Of course, that will require more work...

not familiar with it, and not sure what ramifications it might have :-/ (typically I am too skeptical while trying to replace some core widely used component with another "promising" one)

**Comment by yarikoptic** [comment]
eh, 2.7 and 3.6 are still failing on travis with smth like
```
5.88s$ tox
.package create: /home/travis/build/brechtm/citeproc-py/.tox/.package
.package installdeps: rnc2rng>=2.6.1,!=2.6.2, setuptools, wheel
py27 create: /home/travis/build/brechtm/citeproc-py/.tox/py27
py27 installdeps: nose
py27 inst: /home/travis/build/brechtm/citeproc-py/.tox/.tmp/package/1/citeproc-py-0.5.1+16.g8fb2f23.tar.gz
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/brechtm/citeproc-py/.tox/py27/log/py27-2.log
================================== log start ===================================
Processing ./.tox/.tmp/package/1/citeproc-py-0.5.1+16.g8fb2f23.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-req-build-npUild/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-npUild/
```
@jwodder -- any ideas?  I am out

**Comment by brechtm** [comment]
rnc2rng adds a lot of complexity. Perhaps we need to include its output in the repository after all?

**Comment by yarikoptic** [comment]
> Moving to Poetry for dependency management would prevent these issues as it locks dependencies at specific versions.

FWIW: locking versions would complicate packaging of citeproc-py for Debian and other distributions.

> The rnc2rng step adds a lot of complexity (requires custom code in setup.py). Perhaps we need to include its output in the repository after all?

dunno -- I personally dislike relying on "precompiled" artifacts.  Yet another alternative could be to use it at runtime and cache the result.

**Comment by yarikoptic** [comment]
with setuptools min version specification, we got one step further, thanks @jwodder !  now we are somewhat back at
```
py36 inst: /home/travis/build/brechtm/citeproc-py/.tox/.tmp/package/1/citeproc-py-0.5.1+17.gc078eef.tar.gz
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/brechtm/citeproc-py/.tox/py36/log/py36-2.log
================================== log start ===================================
Processing ./.tox/.tmp/package/1/citeproc-py-0.5.1+17.gc078eef.tar.gz
  Could not find a version that satisfies the requirement rnc2rng!=2.6.2,>=2.6.1 (from versions: 2.4.1, 2.5, 2.6)
No matching distribution found for rnc2rng!=2.6.2,>=2.6.1
```
for python 3.6 on travis  (through tox) , but not on github OSX (there no complaints, but do not see which rnc2rng is installed if any, failing coveralls upload), and windows fails tests suite as before. 
coveralls - someone understood from looking at tox.ini -- runs only for py36 and since none other succeeds for 3.6, fails only for OSX.  I will switch to run cov with py38, and will remove 3.5 right here since long long gone.

**Comment by yarikoptic** [comment]
d'oh silly me -- I am submitting from a fork.  No secrets are thus available. and that is the reason why run has failed for me.  So last commit is likely not needed.

Anyways -- `master` has green CI now. Although AFAIK moving setup requires to pyproject.toml is the right thing to do, we can postpone on this part ;-)

**Pull request closed without merging**
