### PR TITLE
Add GitHub Actions workflow for testing on macOS & Windows

### LINKED ISSUE #107: Add CI setup or testing on Windows and OSX
So to test correct functioning and prevent issues like #106 etc to appear.

could be appveyor or github actions.  Should be quite straightforward.  @jwodder - would you be kind to provide one, probably github actions since we are most familiar with that one.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #107.

### CODE REVIEW

**Comment by jwodder** [comment]
The workflow is failing [on my fork](https://github.com/jwodder/citeproc-py/actions) because `setup.py` is trying to open a file (`citeproc/data/schema/csl.rnc`) that doesn't exist.  I don't see how this code ever worked.

**Comment by jwodder** [comment]
FYI, the workflow is running [on my fork](https://github.com/jwodder/citeproc-py/actions).  Currently, the macOS tests are passing but the Windows ones are not, and I don't know why.

**Comment by yarikoptic** [comment]
I will wait for Travis to finish and then merge. We will fix windows.
Thank you!!

**Comment by yarikoptic** [comment]
travis is green, so to ease testing of windows failure fix in a PR to completion (I will try to look into it later today/tomorrow in windows vm), merging. if anything - we could always disable testing on windows ;)

**Pull request merged**
