### PR TITLE
Bug/mla

### PR DESCRIPTION
**Pull request by terrasea2**
Trello Card: https://trello.com/c/ACoxWp5B/3714-2-how-to-cite-information-incorrect-for-mla-citation-style

### CODE REVIEW

**Comment by yarikoptic** [comment]
not sure if this PR was intended to be this dirty.  Trello card is "Card not found. This card may be on a private board. You may be able to view it by logging in." so I personally a bit lost what is the goal/motivation for this PR.

**Comment by terrasea2** [comment]
Sorry wrong repository

**Comment by brechtm** [comment]
@terrasea2 Please consider creating pull requests to get bugfixes into the main citeproc-py branch.

**Comment by terrasea2** [comment]
No, this is not meant for consumption other than our private platform. I'm sorry about the confusion, but this PR that I've closed, was done in error. None of the changes are applicable to anyone but us. Though you are free to use the branch we created if you choose.

**Pull request closed without merging**
